# -*- coding: utf-8 -*-
"""modular calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1if6hU5-P2Fk4YkdKF34zEGfeQkpfB6CS
"""

import math
import json
import os
from datetime import datetime

HISTORY_FILE = "calc_history.json"

class HumanoidCalculator:
    def __init__(self):
        self.history = self._load_history()
        self.memory = None
        self.greet()

    def greet(self):
        print("="*50)
        print("Hello! I'm HumaCalc — your friendly modular calculator.")
        print("I can do arithmetic, trig (degrees), statistics, unit conversion, and save history.")
        print("Type 'help' to see modules, or 'exit' to quit.")
        print("="*50)

    def _load_history(self):
        if os.path.exists(HISTORY_FILE):
            try:
                with open(HISTORY_FILE, "r") as f:
                    return json.load(f)
            except Exception:
                return []
        return []

    def _save_history(self):
        try:
            with open(HISTORY_FILE, "w") as f:
                json.dump(self.history, f, indent=2)
        except Exception as e:
            print("Could not save history:", e)

    def _record(self, module, expr, result):
        entry = {
            "time": datetime.now().isoformat(sep=" ", timespec="seconds"),
            "module": module,
            "expression": expr,
            "result": result
        }
        self.history.append(entry)
        if len(self.history) > 500:
            self.history = self.history[-500:]
        self._save_history()

    def _parse_numbers(self, s):
        s = s.replace(',', ' ')
        parts = [p for p in s.split() if p.strip()]
        nums = []
        for p in parts:
            if p.upper() == 'M' and self.memory is not None:
                nums.append(float(self.memory))
            else:
                nums.append(float(p))
        return nums

    def arithmetic(self):
        print("\n Arithmetic Module — type expressions like '4 + 5' or '12 * M' (M = memory).")
        expr = input("Expression: ").strip()
        if not expr:
            print("No input detected. Returning to main.")
            return
        try:
            safe_expr = expr.replace('M', f"({self.memory})") if self.memory is not None else expr
            if any(c.isalpha() for c in safe_expr if c not in " "):
                raise ValueError("Alphabets not allowed in arithmetic expression (except M for memory).")
            result = eval(safe_expr, {"__builtins__": None}, {})
            print(f"= {result}")
            self._record("arithmetic", expr, result)
        except Exception as e:
            print(" Couldn't evaluate expression:", e)

    def trig(self):
        print("\n Trigonometry Module — Enter angle in degrees.")
        try:
            angle = float(input("Angle (degrees): ").strip())
            print("Functions available: sin, cos, tan")
            fn = input("Choose function: ").strip().lower()
            rad = math.radians(angle)
            if fn == "sin":
                res = math.sin(rad)
            elif fn == "cos":
                res = math.cos(rad)
            elif fn == "tan":
                res = math.tan(rad)
            else:
                print("Unknown function. Try sin/cos/tan.")
                return
            print(f"{fn}({angle}°) = {res}")
            self._record("trig", f"{fn}({angle})", res)
        except Exception as e:
            print(" Input error:", e)

    def statistics(self):
        print("\n Statistics Module — Enter numbers separated by spaces or commas (support 'M' for memory).")
        s = input("Numbers: ").strip()
        try:
            nums = self._parse_numbers(s)
            if not nums:
                print("No numbers found.")
                return
            n = len(nums)
            mean = sum(nums) / n
            sorted_nums = sorted(nums)
            if n % 2 == 1:
                median = sorted_nums[n//2]
            else:
                median = (sorted_nums[n//2 - 1] + sorted_nums[n//2]) / 2
            variance = sum((x - mean) ** 2 for x in nums) / n
            stdev = math.sqrt(variance)
            print(f"Count: {n}, Mean: {mean}, Median: {median}, StdDev: {stdev}")
            self._record("statistics", s, {"mean": mean, "median": median, "stdev": stdev})
        except Exception as e:
            print(" Could not compute statistics:", e)

    def unit_conversion(self):
        print("\n Unit Conversion — e.g., '10 km to m' or '100 F to C'.")
        s = input("Convert: ").strip().lower()
        try:
            parts = s.split()
            if 'to' not in parts or len(parts) < 4:
                raise ValueError("Format: '<value> <from_unit> to <to_unit>'")
            to_idx = parts.index('to')
            val = float(parts[0])
            from_u = parts[1]
            to_u = parts[to_idx + 1]
            temp_units = {'c','f','k'}
            length_units = {'m','km','cm','mm','mi','ft','in'}
            if from_u in temp_units or to_u in temp_units:
                res = self._convert_temperature(val, from_u, to_u)
            elif from_u in length_units or to_u in length_units:
                res = self._convert_length(val, from_u, to_u)
            else:
                raise ValueError("Unsupported units.")
            print(f"Result: {res}")
            self._record("unit_conversion", s, res)
        except Exception as e:
            print(" Conversion error:", e)

    def _convert_length(self, val, fu, tu):
        factors_to_m = {'m':1, 'km':1000, 'cm':0.01, 'mm':0.001, 'mi':1609.344, 'ft':0.3048, 'in':0.0254}
        if fu not in factors_to_m or tu not in factors_to_m:
            raise ValueError("Unsupported length unit.")
        m = val * factors_to_m[fu]
        return m / factors_to_m[tu]

    def _convert_temperature(self, val, fu, tu):
        fu, tu = fu.lower(), tu.lower()
        if fu == 'c':
            c = val
        elif fu == 'f':
            c = (val - 32) * 5/9
        elif fu == 'k':
            c = val - 273.15
        else:
            raise ValueError("Unknown temp unit")
        if tu == 'c':
            return c
        if tu == 'f':
            return c * 9/5 + 32
        if tu == 'k':
            return c + 273.15
        raise ValueError("Unknown temp unit")

    def memory_menu(self):
        print("\n Memory Menu — store and recall a single value (M).")
        print("Options: store <value>, recall, clear")
        cmd = input(">>> ").strip().lower()
        if cmd.startswith("store"):
            try:
                val = float(cmd.split()[1])
                self.memory = val
                print(f"Stored {val} in memory (M).")
                self._record("memory", "store", val)
            except Exception as e:
                print(" Use: store <number>")
        elif cmd == "recall":
            print(f"Memory (M) = {self.memory}")
        elif cmd == "clear":
            self.memory = None
            print("Memory cleared.")
        else:
            print("Unknown memory command.")

    def show_history(self):
        print("\n Last 20 History Entries:")
        for e in self.history[-20:]:
            print(f"{e['time']} | {e['module']} | {e['expression']} => {e['result']}")

    def help(self):
        print("""
Available modules:
- arithmetic   : Evaluate expressions (supports M for memory)
- trig         : sin/cos/tan (degrees)
- statistics   : mean, median, stddev for list of numbers
- convert      : Unit conversion (length & temperature)
- memory       : store/recall a number (M)
- history      : show session history
- help         : show this message
- exit         : quit the program
""")

    def run(self):
        while True:
            cmd = input("\nWhich module would you like? (type 'help' for options) >>> ").strip().lower()
            if cmd in ("exit", "quit"):
                print(" Bye! MCalc saved your session.")
                break
            elif cmd == "arithmetic":
                self.arithmetic()
            elif cmd == "trig":
                self.trig()
            elif cmd == "statistics":
                self.statistics()
            elif cmd in ("convert", "unitconvert", "unit conversion"):
                self.unit_conversion()
            elif cmd == "memory":
                self.memory_menu()
            elif cmd == "history":
                self.show_history()
            elif cmd == "help":
                self.help()
            else:
                print("I didn't recognize that. Try 'help' to see modules.")

calc = HumanoidCalculator()
calc.run()

